name: CommandAlias
main: de.elliepotato.commandalias.CommandAlias
version: 1.2-RELEASE
author: xEline
description: Easy, Lightweight plugin for easy command aliases.
website: www.elliepotato.de

commands:
  ca:
    description: CommandAlias in-game manager