name: CommandAlias
main: de.elliepotato.commandalias.CommandAlias
version: 1.4.2-RELEASE
api-version: 1.15
author: xEline
description: Easy, Lightweight plugin for easy command aliases.
website: www.elliepotato.de
softdepend: [PlaceholderAPI]

commands:
  ca:
    description: CommandAlias in-game manager